version: '3.6'

services:
  app-php:
    container_name: practice_php_Ignacio
    image: php:8.0-apache
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:80"
